Downloading Libraries

In [2]:
!pip install pandas
!pip install numpy

Collecting pandas
  Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 26.5 MB/s  0:00:00m0:00:010:01
Downloading numpy-2.4.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 34.0 MB/s  0:00:00m0:00:0100:01
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Installing collected packages: pytz, numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]2m2/3 [pandas]
Successfully installed numpy-2.4.0 pandas-2.3.3 pytz-2025.2
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.4.0)

Libraries Import

In [3]:
import pandas as pd
import numpy as np

Q1

In [6]:
df = pd.read_csv('customer_data.csv')

Q2

In [7]:
df.head(5)

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
0,Dr.,Ray,Morton,sebvajom@kol.km,Male,38,Medtronic Inc.,Health Therapist,(987) 619-2695,B6V 3W3,MB,5020000000000230,05/2018,Solo,8.36,Blue,126.23.139.2,Sunday,pm,04/05/1930
1,Miss,Claudia,Rodriquez,acu@jatsot.ug,Female,51,"Ames Department Stores, Inc.",Health Therapist,(356) 736-7352,G7M 5F3,SK,5020000000000230,07/2028,Visa,68.31,Black,106.198.76.211,Tuesday,am,12/20/1926
2,Miss,Harry,Meyer,zuz@lo.wf,Female,51,CSX Corp.,Political Scientist,(539) 246-1806,A0Z 6P9,NS,6300000000000000,02/2023,Switch,34.65,Black,186.150.187.29,Wednesday,pm,08/20/1931
3,Miss,Edith,Gilbert,hansohsi@jupec.md,Female,55,Murphy Oil Corporation,Transportation Manager,(984) 962-7494,P9I 9H3,YT,3530000000000000,02/2028,Maestro,64.59,White,80.140.57.161,Saturday,am,06/18/2001
4,Dr.,Lura,Murphy,webediti@je.st,Female,20,PETsMART Inc,Statistician,(902) 568-9748,S1A 6K0,ON,4030000000000000,10/2025,Diners Club International,20.83,Yellow,211.103.43.41,Friday,pm,06/14/2045

Q3

In [8]:
df.shape

(30000, 20)

Q4

In [9]:
df["age"].agg(['max','min','mean'])

max     65.000000
min     18.000000
mean    41.550067
Name: age, dtype: float64

Q5

In [10]:
df['first'].value_counts().head(3).index.tolist()

['Willie', 'Francis', 'Eula']

Q6

In [11]:
double = df['phone'].value_counts().index[0]
df[df['phone'] == double]

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
15,Mrs.,Lilly,Tyler,kofadu@itohi.tf,Female,38,CSX Corp.,Structural Engineer,(263) 382-8004,V7K 1E3,ON,30000000000000,11/2022,Diners Club Carte Blanche,9.61,Yellow,74.124.37.227,Saturday,am,03/30/1985
16,Mrs.,Peter,Cain,megkosig@anazeor.gn,Male,27,Campbell Soup Co.,Insurance Adjuster,(263) 382-8004,E8T 2B4,YT,3530000000000000,03/2024,Solo,13.74,Black,25.207.141.135,Tuesday,am,08/05/1950

Q7

In [12]:
str_engineers = df[df['profession'] == 'Structural Engineer']
len(str_engineers)

87

Q8

In [13]:
male_str_engineers = str_engineers[str_engineers['gender'] == 'Male']
len(male_str_engineers)

43

Q9

In [14]:
AB_female_str_engineers = str_engineers[(str_engineers['province'] == 'AB') & (str_engineers['gender'] == 'Female')]
AB_female_str_engineers

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
8858,Dr.,Roy,Stanley,apiunvo@ehasom.ir,Female,39,Cincinnati Financial Corp.,Structural Engineer,(876) 758-2929,N5A 6L2,AB,6300000000000000,02/2022,InstaPayment,31.86,Red,165.249.159.57,Sunday,pm,12/25/1903
9058,Mr.,Lora,Kennedy,dennap@rabac.se,Female,51,BJ Services Company,Structural Engineer,(305) 786-6959,N3R 4B7,AB,201000000000000,06/2019,Diners Club United States & Canada,53.29,Black,42.216.243.206,Thursday,pm,06/06/2028
24736,Mrs.,Nell,Richards,dob@me.ki,Female,18,Telephone & Data Systems Inc,Structural Engineer,(262) 681-5018,N3Y 3G2,AB,347000000000000,07/2028,American Express,76.28,Blue,91.16.30.156,Wednesday,pm,07/14/1951
29865,Mrs.,Don,McDaniel,naf@zudu.bj,Female,37,Anadarko Petroleum Corporation,Structural Engineer,(238) 789-2825,B4A 8Q9,AB,5610000000000000,12/2022,Mastercard,62.71,Blue,162.233.117.142,Sunday,pm,11/03/1989

Q10

In [15]:
df["price(CAD)"].agg(['max','min','mean'])

max     100.000000
min       0.000000
mean     49.990775
Name: price(CAD), dtype: float64

Q11

In [16]:
df[df['price(CAD)'] == 0]

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
5320,Dr.,Bruce,Bryan,ru@pubuspuh.cl,Male,59,Wal-Mart Stores Inc,Engineer Technician,(709) 446-8317,H6H 3Y0,NU,201000000000000,04/2024,Bankcard,0.0,White,82.70.62.64,Wednesday,am,12/11/1900
10597,Mrs.,Flora,Clark,wad@me.com,Female,27,MetLife Inc.,Cruise Director,(775) 373-6590,B2U 8K6,NB,30100000000000,05/2020,Diners Club Carte Blanche,0.0,Red,231.156.15.63,Thursday,pm,08/22/1904

Q12

In [17]:
df[df['price(CAD)'] >= 100]

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
76,Mrs.,Gregory,Brown,hav@jek.gs,Female,31,"E*Trade Group, Inc.",Novelist,(625) 537-8923,X3S 4Q2,PE,6010000000000000,04/2018,Visa,100.0,Green,212.100.18.95,Monday,am,10/23/2063
21093,Mrs.,Cody,Christensen,get@jovu.ag,Male,28,National City Corp.,Hospital Administrator,(261) 737-3292,X0S 1O5,PE,201000000000000,03/2024,JCB,100.0,Green,168.48.19.165,Wednesday,pm,03/28/1955
24385,Miss,Lizzie,Dixon,goh@tuwjaz.gd,Female,38,FleetBoston Financial Co.,Compensation Analyst,(989) 239-1752,V8X 9V6,NB,6300000000000000,07/2019,Bankcard,100.0,Blue,140.87.99.78,Saturday,pm,03/03/1983

Q13

In [18]:
df[df['cc_no'] == 5020000000000230]

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date
0,Dr.,Ray,Morton,sebvajom@kol.km,Male,38,Medtronic Inc.,Health Therapist,(987) 619-2695,B6V 3W3,MB,5020000000000230,05/2018,Solo,8.36,Blue,126.23.139.2,Sunday,pm,04/05/1930
1,Miss,Claudia,Rodriquez,acu@jatsot.ug,Female,51,"Ames Department Stores, Inc.",Health Therapist,(356) 736-7352,G7M 5F3,SK,5020000000000230,07/2028,Visa,68.31,Black,106.198.76.211,Tuesday,am,12/20/1926

Q14

In [19]:
df['cc_exp_year'] = pd.to_datetime(df['cc_exp'], format='%m/%Y').dt.year
df[df['cc_exp_year'] == 2019].drop_duplicates(subset = 'cc_no')

,prefix,first,last,email,gender,age,company,profession,phone,postal,...,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date,cc_exp_year
45,Mrs.,Winifred,Henderson,ezamaw@radi.kn,Female,43,Western Digital Inc,Relocation Manager,(250) 572-7482,K9C 2D2,...,6300000000000000,12/2019,Laser,99.49,Blue,196.43.87.187,Wednesday,pm,07/21/2051,2019
46,Miss,Carolyn,Horton,dehje@mowakbo.tj,Male,22,Stewart & Stevenson Services Inc,Employment Agent,(737) 647-5446,L1F 9E3,...,4900000000000000,07/2019,InstaPayment,44.46,Yellow,135.153.126.179,Wednesday,pm,07/25/2010,2019
49,Miss,Virgie,Adams,lodbinogu@ir.edu,Male,56,Maxtor Corporation,Systems Programmer,(764) 601-4889,B2O 6Z0,...,3530000000000000,02/2019,Diners Club Carte Blanche,66.05,Red,175.149.148.141,Monday,am,05/15/2047,2019
60,Mrs.,Blake,Hart,nup@pov.nc,Female,46,Kindred Healthcare Inc.,Computer Graphics Specialist,(719) 605-1004,X0O 5E1,...,5480000000000000,10/2019,InstaPayment,89.87,White,164.16.206.229,Sunday,am,05/05/1942,2019
66,Miss,Leila,Carpenter,ke@wufiol.wf,Male,21,W.W. Grainger Inc,Artist,(816) 775-3467,E5X 5V9,...,5140000000000000,11/2019,Visa Electron,29.63,Green,99.203.101.232,Tuesday,am,01/28/1936,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26232,Mr.,Seth,Ballard,fofaw@nofuwosek.kr,Female,54,Kellogg Company,Compliance Manager,(766) 262-3952,M6D 9W4,...,6340000000000000,09/2019,Bankcard,29.87,Yellow,134.218.30.37,Friday,am,02/06/2004,2019
26312,Mrs.,Katie,Kelly,awo@vodofi.iq,Male,24,Regis Corporation,TV Programmer,(412) 291-8115,M8N 0X8,...,4420000000000000,06/2019,Discover Card,80.13,White,118.34.232.140,Sunday,am,05/26/2066,2019
28479,Miss,Edgar,Davidson,ni@epgo.ec,Female,32,OM Group Inc,Accountant,(542) 587-3618,N7F 3H3,...,4650000000000000,11/2019,Bankcard,20.81,White,85.139.51.147,Wednesday,am,08/28/2045,2019
28915,Mrs.,Mabel,Sparks,ruki@kisga.bh,Female,19,Bethlehem Steel Corporation,Inside Sales,(408) 733-4417,N2N 1T5,...,4940000000000000,04/2019,Bankcard,25.51,White,206.237.116.180,Friday,pm,02/25/2001,2019
29719,Dr.,Seth,Barnes,joornuc@rizci.id,Female,41,Convergys Corp.,Lab Services Director,(374) 457-2147,R1N 2C2,...,4840000000000000,02/2019,Diners Club United States & Canada,7.90,Yellow,70.153.100.208,Sunday,pm,02/01/2028,2019

Q15

In [20]:
len(df[df['cc_type'] == 'Visa'])

1721

Q16

In [21]:
df[(df['cc_type'] == 'Visa') & (df['price(CAD)'] == 100)]

,prefix,first,last,email,gender,age,company,profession,phone,postal,...,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date,cc_exp_year
76,Mrs.,Gregory,Brown,hav@jek.gs,Female,31,"E*Trade Group, Inc.",Novelist,(625) 537-8923,X3S 4Q2,...,6010000000000000,04/2018,Visa,100.0,Green,212.100.18.95,Monday,am,10/23/2063,2018

Q17

In [25]:
df['profession'].value_counts().head(2).index.tolist()

['Preschool Teacher', 'Distribution Manager']

Q18

In [26]:
df['email_provider'] = df['email'].str.split('@').str[1]
df['email_provider'].value_counts().head(5).index.tolist()

['gmail.com', 'me.com', 'outlook.com', 'live.com', 'hotmail.com']

Q19

In [27]:
df[df['email_provider'] == 'am.edu']

,prefix,first,last,email,gender,age,company,profession,phone,postal,...,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,ampm,date,cc_exp_year,email_provider
150,Miss,Loretta,Fletcher,barit@am.edu,Female,48,York International Corp,Rehabilitation Counselor,(323) 279-8038,E5X 8L0,...,05/2021,Diners Club United States & Canada,97.26,White,147.57.240.225,Monday,am,11/07/2066,2021,am.edu

Q20

In [28]:
df['weekday'].value_counts().head(1).index.tolist()

['Saturday']